# VERSION 1.0 (apache-superset)
# AUTHOR: Mohamed Abdultawab <mohamedtoba96@gmail.com>

version: "3"

services:

  redis:
    image: redis:3.2
    container_name: superset_cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  db:
    env_file: .env
    image: postgres:10
    container_name: superset_db
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - db_home:/var/lib/postgresql/data

  superset_app:
    build:
      context: .
      args:
        SUPERSET_VERSION: ${SUPERSET_VERSION}
    container_name: superset_app
    restart: always
    env_file: .env
    ports:
      - 8088:8088
      - 5555:5555
    depends_on:
      - db
      - redis
    volumes:
      - ./config/:/home/superset/config/

volumes:
  db_home:
    external: false
  redis:
    external: false
